### PR TITLE
Update Android X

### PR DESCRIPTION
**Pull request by searchy2**
*Update TargetSDK to v28.
*Update Support Dependencies to Android X.
*Update Glide to v4.8.0.

### CODE REVIEW

**Comment by searchy2** [comment]
AndroidX uses different and independent library version numbers. That means Support could be on v1.0.0 while design is on v2.0.0.

**Comment by yarolegovich** [comment]
Please add the library that now contains ActivityTestRule and make sure all :library module androidTests pass, I will then merge your PR. Thanks.

**Comment by searchy2** [comment]
Nice catch. All tests look good! 
maxthonsnap20180926114110

**Comment by searchy2** [comment]
Can this be merged?

**Comment by moisoni97** [comment]
Please merge, version `implementation 'com.yarolegovich:discrete-scrollview:1.4.9'` doesn't work with AndroidX!

**Comment by tatocaster** [comment]
Please update. AndroidX is still not supported

**Comment by bernaferrari** [comment]
So.. any progress?

**Comment by emalamela** [comment]
Is this being blocked by something? Can I be of help in any way for this be merged?

**Comment by searchy2** [comment]
Any updates on this PR?

**Comment by mamatagelanee07** [comment]
@yarolegovich Can we merge this PR?

**Comment by pandelisgreen13** [comment]
Any updates on this PR?

**Comment by searchy2** [comment]
Thanks, let me update the dependencies and Glide to v4.10 before merging.

The latest version of Glide breaks compatibility with older versions so let’s get the newest in this PR.

**Pull request closed without merging**
